import { useMutation } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";

export type ClassifyResult = {
  tierId: number | null;
  tierName: string | null;
  confidence: number;
  subcategories: string[];
  text: string;
};

/**
 * Calls the classify-interest edge function (Mistral Agent).
 * Returns the best-matching tier id, confidence, and 1-3 dynamic
 * subcategories generated by the LLM.
 */
export function useClassifyInterest() {
  return useMutation({
    mutationFn: async (text: string): Promise<ClassifyResult | null> => {
      const trimmed = text.trim();
      if (trimmed.length < 2) return null;
      const { data, error } = await supabase.functions.invoke("classify-interest", {
        body: { text: trimmed },
      });
      if (error) throw error;
      if (!data) return null;
      return {
        tierId: data.tierId ?? null,
        tierName: data.tierName ?? null,
        confidence: Number(data.confidence) || 0,
        subcategories: Array.isArray(data.subcategories) ? data.subcategories : [],
        text: data.text ?? trimmed,
      };
    },
  });
}

const STOPWORDS = new Set([
  "the", "and", "for", "with", "from", "into", "this", "that", "these", "those",
  "what", "when", "where", "why", "how", "who", "which", "is", "are", "was",
  "were", "been", "being", "have", "has", "had", "do", "does", "did", "of",
  "in", "on", "at", "to", "by", "as", "an", "a", "or", "but", "not", "no",
  "yes", "i", "you", "he", "she", "it", "we", "they", "my", "your", "their",
  "our", "his", "her", "its",
]);

export function extractKeywords(text: string, max = 5): string[] {
  return Array.from(
    new Set(
      text
        .toLowerCase()
        .replace(/[^\p{L}\p{N}\s]/gu, " ")
        .split(/\s+/)
        .filter((w) => w.length >= 4 && !STOPWORDS.has(w)),
    ),
  ).slice(0, max);
}

async function upsertTierKeyword(
  userId: string,
  tierId: number,
  keyword: string,
  kind: "keyword" | "subcategory",
) {
  const { data: existing } = await supabase
    .from("tier_keywords")
    .select("id, count")
    .eq("user_id", userId)
    .eq("tier_id", tierId)
    .eq("keyword", keyword)
    .eq("kind", kind)
    .maybeSingle();
  if (existing) {
    await supabase
      .from("tier_keywords")
      .update({ count: existing.count + 1, last_seen: new Date().toISOString() })
      .eq("id", existing.id);
  } else {
    await supabase
      .from("tier_keywords")
      .insert({ user_id: userId, tier_id: tierId, keyword, kind });
  }
}

/**
 * Upserts each extracted keyword into `tier_keywords` (kind='keyword').
 */
export async function persistKeywords(userId: string, tierId: number, keywords: string[]) {
  if (!keywords.length) return;
  for (const keyword of keywords) {
    await upsertTierKeyword(userId, tierId, keyword, "keyword");
  }
}

/**
 * Upserts AI-generated semantic subcategories (kind='subcategory').
 * These are the structured zero-party signal that powers per-user
 * personalised tier cards in the Interests Tiers section.
 */
export async function persistSubcategories(userId: string, tierId: number, subs: string[]) {
  if (!subs.length) return;
  for (const sub of subs) {
    await upsertTierKeyword(userId, tierId, sub, "subcategory");
  }
}
